
[[constraint]]
  name = "gitlab.com/OrangeX/backend/golibs/logger.git"
  version = "=1.0.1"

[[constraint]]
  name = "gitlab.com/OrangeX/backend/golibs/kafka-mapper.git"
  version = "1.4.1"

[[constraint]]
  name = "gitlab.com/OrangeX/backend/golibs/requests.git"
  version = "=1.4.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "=1.6.2"

